### ISSUE TITLE
Error when running demo_all.py

### ISSUE THREAD

**Issue by alchemyst** [SimonStreicher/FaultMap#13]
<pre>
INFO:root:Running demo_looprank.py
INFO:root:Running scenario simple5
INFO:root:Number of tags: 5
Traceback (most recent call last):
  File "demo_all.py", line 18, in <module>
    runall('demo_*.py', ['demo_all.py'])
  File "demo_all.py", line 15, in runall
    execfile(f)
  File "demo_looprank.py", line 24, in <module>
    m, alpha)
  File "/Users/alchemyst/Documents/Subjects/students/2014/streicher_s/LoopRank/ranking/noderank.py", line 475, in looprank_static
    calc_maingainrank(modgainmatrix, noderankdata, m)
TypeError: calc_maingainrank() takes exactly 5 arguments (3 given)
</pre>

**Comment by SimonStreicher** [comment]
`demo_all.py` is no longer part of the code base - testing is now performed via nosetests
