### ISSUE TITLE
TypeError: No matching overloads found for infodynamics.measures.discrete.TransferEntropyCalculatorDiscrete.addObservations(map,map)

### ISSUE THREAD

**Issue by fmgvalente** [SimonStreicher/FaultMap#26]
Hi, got an exception when attempting to use faultmap with the gpu enabled:
I'm using the latest faultmap from the repo and jidt 1.5 compiled with gpu support

What can be done here? It seems it attempts to call a non-existent method.

Kind Regards,
Frederico Valente

INFO:root:Analysing effect of: raiseXERError[SIF-0127] on LRT::SignalPublisher::publish_signals[LRT-0010] for box number: 1
INFO:root:Now testing delay: 0
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/fault_map_env/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/fault_map_env/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/fault_map_env/lib/python3.7/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/app/FaultMap/faultmap/gaincalc_oneset.py", line 211, in calc_weights_oneset
    affectedvarindex,
  File "/app/FaultMap/faultmap/gaincalculators.py", line 549, in calcweight
    **self.parameters
  File "/app/FaultMap/faultmap/transentropy.py", line 201, in calc_infodynamics_te
    teCalc.addObservations(source, dest)
TypeError: No matching overloads found for infodynamics.measures.discrete.TransferEntropyCalculatorDiscrete.addObservations(map,map), options are:
        public void infodynamics.measures.discrete.TransferEntropyCalculatorDiscrete.addObservations(int[],int[],boolean[])
        public void infodynamics.measures.discrete.TransferEntropyCalculatorDiscrete.addObservations(int[],int[],int,int)
        public void infodynamics.measures.discrete.TransferEntropyCalculatorDiscrete.addObservations(int[],int[])
        public void infodynamics.measures.discrete.TransferEntropyCalculatorDiscrete.addObservations(int[][][],int,int,int,int)
        public void infodynamics.measures.discrete.TransferEntropyCalculatorDiscrete.addObservations(int[][],int,int)
        public void infodynamics.measures.discrete.TransferEntropyCalculatorDiscrete.addObservations(int[][][],int,int)
        public void infodynamics.measures.discrete.TransferEntropyCalculatorDiscrete.addObservations(int[][],int)

        at findOverload(native/common/jp_method.cpp:242)
        at findOverload(native/common/jp_method.cpp:245)
        at invoke(native/common/jp_method.cpp:253)
        at __call__(native/python/pyjp_method.cpp:142)

"""

**Comment by SimonStreicher** [comment]
Sorry for only seeing this now, I haven't really been paying attention to this repo but plan on expanding it significantly this year.

I'd guess it most probably have to do with the data type not being passed as int, I'll see if I can implement some proper checks on data types. It will also be important to think about handling missing values here, as NaN is not an int concept.
